# Course - Introduction to R 

##### NOTE: 
1. Your code MUST execute without any errors. 
2. You can add more lines in your code as required.

## Section 1: Data Types and Operations Pt. 1

### Question 1 
**Create the variables with the following composition:**
1. A vector containing each letter of your first name as its elements.
2. A variable that contains your name concatenated from the vector created in (1)
3. A variable containing a sequence from 100 to 120.
4. Create a matrix of 3x3 dimensions that contains the even sequence of numbers starting from 2.
5. Assign names to the variables.

In [ ]:
#### Start solution ####

In [4]:
n <- c("S","a","r","a","h")
print(n)

[1] "S" "a" "r" "a" "h"


In [9]:
#name = paste(n[1], n[2], n[3], n[4], n[5], sep ='')
name = paste(n, collapse = '')
name

[1] "Sarah"

In [10]:
seq <- 100:120
seq

[1] 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118
[20] 119 120

In [12]:
mat <- seq(from = 2, length.out = 18, by = 2)
dim <- c(3, 3)
arr <- array( mat , dim )
arr

[,1] [,2] [,3]
[1,] 2     8   14  
[2,] 4    10   16  
[3,] 6    12   18

In [ ]:
#### End solution ####

### Question 2
**Create a factor variable emp_status:**
1. Containing the categorical variables: Employed, Unemployed, Self-Employed, with each level appearing atleast more than 2.
2. Display the levels and the factor variable as a table.
3. Unclass the elements of the factor variable.

In [4]:
#### Start solution ####

In [75]:
data = c("Employed","Unemployed","Employed","Employed","Self-Employed","Unemployed","Self-Employed","Unemployed","Self-Employed","Employed","Self-Employed")
levels = c("Employed","Unemployed","Self-Employed")
emp_status <- factor(data,levels)
emp_status

[1] Employed      Unemployed    Employed      Employed      Self-Employed
 [6] Unemployed    Self-Employed Unemployed    Self-Employed Employed     
[11] Self-Employed
Levels: Employed Unemployed Self-Employed

In [76]:
t = table(emp_status)
t

emp_status
     Employed    Unemployed Self-Employed 
            4             3             4 

In [8]:
unclass(emp_status)

[1] 1 2 1 2 1 3 2 3 2 3 1 3
attr(,"levels")
[1] "Employed"      "Unemployed"    "Self-Employed"

In [3]:
#### End solution ####

### Question 3
**Create a dataframe object called bank_customers:**
1. the data frame will have three columns: CustomerID, hasAccount, totalBalance
2. Fill the data as follows
    a. Alicia does not have an account. She is here for inquiry 
    b. Nancy is here to check on her account balance of USD 10,000.
    c. Fernando is here to deposit USD 100 in his account which had no balance.
    d. Louis will withdraw all his money from the account that had USD 2,000. 
    e. Diane is here for information. 
3. For customers that do not have a value, use NA as placeholder.
4. Print the number of rows, columns and names for the data frame.

In [ ]:
#### Start solution ####

In [54]:
df <- data.frame(matrix(ncol = 3, nrow = 5))
colnames(df) <- c("CustomerID", "hasAccount", "totalBalance")
row.names(df) = c("a","b","c","d","e")
df

CustomerID hasAccount totalBalance
1 NA         NA         NA          
2 NA         NA         NA          
3 NA         NA         NA          
4 NA         NA         NA          
5 NA         NA         NA

In [56]:
df["CustomerID"]<-c("Alicia", "Nancy", "Fernando","Louis", "Diane" )
df

CustomerID hasAccount totalBalance
1 Alicia     NA         NA          
2 Nancy      NA         NA          
3 Fernando   NA         NA          
4 Louis      NA         NA          
5 Diane      NA         NA

In [57]:
df["hasAccount"]<-c(NA, "Yes", "Yes","Yes", NA )
df

CustomerID hasAccount totalBalance
1 Alicia     NA         NA          
2 Nancy      Yes        NA          
3 Fernando   Yes        NA          
4 Louis      Yes        NA          
5 Diane      NA         NA

In [58]:
df["totalBalance"]<-c(NA, 10000, 100,NA, NA )
df

CustomerID hasAccount totalBalance
1 Alicia     NA            NA       
2 Nancy      Yes        10000       
3 Fernando   Yes          100       
4 Louis      Yes           NA       
5 Diane      NA            NA

In [73]:
nrow(df)
ncol(df)
colnames(df)
rownames(df)


[1] 5

[1] 3

[1] "CustomerID"   "hasAccount"   "totalBalance"

[1] "a" "b" "c" "d" "e"

In [71]:
#### End solution ####

### Good Job! You have successfully completed the section!

## Section 2: Control Structures 

### Question 1
**Create a variable containing a sequence of numbers from 1 to 100:**
1. Iterate over the variables and print those numbers which are prime.

**Create a variable var with a value of 1:**
1. Create a while loop and increase the value of var at each iteration. 
2. When you reach the 10th prime number, terminate the loop and print the number.

In [5]:
#### Start solution ####

In [ ]:
x <- seq(1:100)
x

In [ ]:
p_num <- c(2)
print(paste(2, "is a prime number"))

for(num in x){
  count <- 0
  
  for(i in 2:(num/2)){
    if(num%%i == 0){
      count <- count+1
      break
    }
  }
  if(count == 0 && num != 1 )    {
    print(paste(num, "is a prime number"))
    p_num <- append(p_num, num)
  }  
}


print(p_num)

In [ ]:
p_num <- c(2)
print(paste(2, "is a prime number"))
var <- 1
a <- 1
while(a != 0){
for(num in x){
    count <- 0
  
  for(i in 2:(num/2)){
    if(num%%i == 0){
      count <- count+1
      break
    }
  }
  if(count == 0 && num != 1 )    {
    print(paste(num, "is a prime number"))
    p_num <- append(p_num, num)
    print(length(p_num))
   
    }

  if(length(p_num)==10){
    a = 0
    break
  }
    var <- var + 1
}
  
}

print(paste(var, "is a value of variable var when we reach 10th prime number"))
print(paste(p_num, "is a list")

In [ ]:
#### End solution ####

### Question 2
**Create a matrix of size 3x3 called mat_1:**
1. Iterate over all the values one by one and print the element as well as the position in the matrix (row, col)

In [9]:
#### Start solution ####

In [ ]:
mat <- matrix(1:9 , nrow =3, ncol = 3)

In [ ]:
print(seq_len(nrow(mat)))

In [ ]:
print(seq_len(ncol(mat)))

In [ ]:
for(i in seq_len(nrow(mat))){
  for(j in seq_len(ncol(mat))){
    print(paste("At position", i, "&", j, "matrix element is:", mat[i,j]))
  }
}

In [ ]:
#### End solution ####

### Good Job! You have successfully completed the section!

## Section 3: Functions

### Question 1
**Create a function called gcd that finds the greatest common divisor of two numbers a and b:**
1. a and b, should be taken as input.
2. The function must print the GCD as well as return it.
3. The output must be saved in a variable called answer.

In [9]:
#### Start solution ####

In [ ]:

gcd <- function(a,b){
  
  if(a<b){
    max <- b
  }   else{
    max <- a
  }
  
  
  for(i in 1:max)  {
    
    if((a%%i)==0 && (b%%i)==0){
      ans <- i
    }
    
  }
  
  print(paste("G.C.D of", a , "and", b, "is" ,ans))
  return(ans)
  
}


In [ ]:
print("please enter two numbers")
n1 <- scan()
n2 <- scan()
gcd(n1,n2)
value <- gcd(n1,n2)

In [14]:
#### End solution ####

### Question 2
**Create a function called allConditionsMeet, that checks whether two expressions evaluate to true:**
1. a and b, should be taken as input.
2. the function should check if a and b, both conditions, evaluate to True.
3. The function must returns a boolean value.
4. Using a method, print the arguments that function takes.

In [9]:
#### Start solution ####

In [ ]:
allconditionsmeet <- function(a,b){
  
  if(a > 0 && b > 0) {
    return(TRUE)
  }else{
    return(FALSE)
  }
}


In [ ]:
print("Enter first number:")
a <- as.integer(readline())
print(a)
print("Enter second number:")
b <- as.integer(readline())
print(b)

result = allconditionsmeet(a,b)
print(paste("Result is", result))

In [14]:
#### End solution ####

### Good Job! You have successfully completed the section!

## Section 4: Vectorized Operations

### Question 1
**Create two matrices matrix_1 and matrix_2 of dimensions 2x3 and 3x2:**
1. Perform element-wise multiplication.
2. Perform matrix multipilcation. 

**Create a 2x2 matrix my_mat:**
1. Write a function to find the determinant of the matrix.

In [9]:
#### Start solution ####

In [8]:
matrix_1 <- matrix(2*(1:6), 2, 3); matrix_2 <- matrix(4*(1:6), 3, 2)
matrix_1
matrix_2

[,1] [,2] [,3]
[1,] 2    6    10  
[2,] 4    8    12

[,1] [,2]
[1,]  4   16  
[2,]  8   20  
[3,] 12   24

In [9]:
matrix_1*matrix_2

ERROR: Error in matrix_1 * matrix_2: non-conformable arrays


In [10]:
matrix_1%*%matrix_2

[,1] [,2]
[1,] 176  392 
[2,] 224  512

In [11]:
my_mat <-matrix(3*(1:4), 2,2)
my_mat


[,1] [,2]
[1,] 3     9  
[2,] 6    12

In [12]:
det(my_mat)

[1] -18

In [14]:
#### End solution ####

### Good Job! You have successfully completed the section!

## Section 5: Date and Time in R

### Question 1
**Use the current date and time and store them into variables curr_date and curr_time respectively: [use sys]**
1. Convert both into date and time objects using the appropriate functions.
2. Print the weekday, year, second and hour using the appropriate function and variables.

In [9]:
#### Start solution ####

In [21]:
x <- Sys.time()
x

[1] "2021-09-23 17:39:20 PKT"

In [22]:
p <-as.POSIXlt(x)
p

[1] "2021-09-23 17:39:20 PKT"

In [23]:
curr_date = as.Date(p, "%m/%d/%Y")
curr_date

[1] "2021-09-23"

In [24]:
curr_time = format(x, "%H:%M:%S")
curr_time

[1] "17:39:20"

In [25]:
print(paste("weekday:", p$wday))
print(paste("year:", p$year))
print(paste("sec:", p$sec))
print(paste("hour:", p$hour))

[1] "weekday: 4"
[1] "year: 121"
[1] "sec: 20.3644390106201"
[1] "hour: 17"


In [14]:
#### End solution ####

### Question 2
**Create a variable to store current date/time**
1. Create another variable that stores and set the timezone as GMT-5
2. Find the difference between your current time and the GMT-5 timezone.

In [9]:
#### Start solution ####

In [2]:
GMT_time <- as.POSIXct("2021-09-23 17:48:34", tz= "Etc/GMT-5")
GMT_time

[1] "2021-09-23 17:48:34 +05"

In [3]:
my_timezone = Sys.time()
my_timezone 

[1] "2021-09-24 14:47:01 PKT"

In [4]:
my_timezone - GMT_time

Time difference of 20.9742 hours

In [14]:
#### End solution ####

### Good Job! You have successfully completed the section!

## Section 6: Loop Functions

### Question 1
**Create a function to calculate mean and standard deviation of the provided data**
1. Create a sequence of numbers from 100 to 150 store in a variable called numbers.
1. Use lapply, sapply, apply and tapply to implement the functions on "numbers" [only on the second half of the sequence for tapply]

In [9]:
#### Start solution ####

In [8]:
numbers <- list(seq(100, 150))
numbers

[[1]]
 [1] 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118
[20] 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
[39] 138 139 140 141 142 143 144 145 146 147 148 149 150

In [17]:
number <- matrix(seq(100, 150))
number


[,1]
 [1,] 100 
 [2,] 101 
 [3,] 102 
 [4,] 103 
 [5,] 104 
 [6,] 105 
 [7,] 106 
 [8,] 107 
 [9,] 108 
[10,] 109 
[11,] 110 
[12,] 111 
[13,] 112 
[14,] 113 
[15,] 114 
[16,] 115 
[17,] 116 
[18,] 117 
[19,] 118 
[20,] 119 
[21,] 120 
[22,] 121 
[23,] 122 
[24,] 123 
[25,] 124 
[26,] 125 
[27,] 126 
[28,] 127 
[29,] 128 
[30,] 129 
[31,] 130 
[32,] 131 
[33,] 132 
[34,] 133 
[35,] 134 
[36,] 135 
[37,] 136 
[38,] 137 
[39,] 138 
[40,] 139 
[41,] 140 
[42,] 141 
[43,] 142 
[44,] 143 
[45,] 144 
[46,] 145 
[47,] 146 
[48,] 147 
[49,] 148 
[50,] 149 
[51,] 150

In [13]:
mean_fn <- function(x) mean(x)
sd_fn <- function(x) sd(x)


In [14]:
lapply(numbers , mean_fn)
lapply(numbers , sd_fn)

[[1]]
[1] 125

[[1]]
[1] 14.86607

In [21]:
sapply(numbers , mean_fn)
sapply(numbers , sd_fn)

[1] 125

[1] 14.86607

In [22]:
apply(number , 2, mean_fn)
apply(number , 2, sd_fn)

[1] 125

[1] 14.86607

In [29]:
f <- gl(2,25)
f

[1] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2
[39] 2 2 2 2 2 2 2 2 2 2 2 2
Levels: 1 2

In [31]:
tapply(seq(101:150) , f, mean_fn)
tapply(seq(101:150) ,f, sd_fn)

1  2 
13 38

1        2 
7.359801 7.359801

In [14]:
#### End solution ####

### Question 2
**Create a matrix of dimensions 4x4**
1. Find the row-wise and column-wise mean of the matrix.
2. Print the values.

In [9]:
#### Start solution ####

In [32]:
mat <- matrix(4*(1:16),4,4)
mat

[,1] [,2] [,3] [,4]
[1,]  4   20   36   52  
[2,]  8   24   40   56  
[3,] 12   28   44   60  
[4,] 16   32   48   64

In [35]:
rowmean = apply(mat, 1, mean_fn)
rowmean

[1] 28 32 36 40

In [36]:
colmean = apply(mat, 2, mean_fn)
colmean

[1] 10 26 42 58

In [37]:
rowMeans(mat)

[1] 28 32 36 40

In [38]:
colMeans(mat)

[1] 10 26 42 58

In [14]:
#### End solution ####

### Good Job! You have successfully completed the section!

## Section 7: Data Split

### Question 1
**Using the data frame Orange:**
1. Using split function to break down the dataset on circumference and store it in 'split_data' variable. 
2. Print the values for split_data where circumference is 30 and 75.
3. Find the average age of the tree when the circumference is 30 and when circumference is 214.


The dataset is loaded and the variable Orange contains the respective dataset.

In [21]:
library(datasets)

In [25]:
head(Orange)

Tree age  circumference
1 1     118  30          
2 1     484  58          
3 1     664  87          
4 1    1004 115          
5 1    1231 120          
6 1    1372 142

In [9]:
#### Start solution ####

In [40]:
split_data = split(Orange,Orange$circumference)
split_data

$`30`
   Tree age circumference
1     1 118            30
15    3 118            30
29    5 118            30

$`32`
   Tree age circumference
22    4 118            32

$`33`
  Tree age circumference
8    2 118            33

$`49`
   Tree age circumference
30    5 484            49

$`51`
   Tree age circumference
16    3 484            51

$`58`
  Tree age circumference
2    1 484            58

$`62`
   Tree age circumference
23    4 484            62

$`69`
  Tree age circumference
9    2 484            69

$`75`
   Tree age circumference
17    3 664            75

$`81`
   Tree age circumference
31    5 664            81

$`87`
  Tree age circumference
3    1 664            87

$`108`
   Tree  age circumference
18    3 1004           108

$`111`
   Tree age circumference
10    2 664           111

$`112`
   Tree age circumference
24    4 664           112

$`115`
   Tree  age circumference
4     1 1004           115
19    3 1231           115

$`120`
  Tree  age circumference
5    1 1231           120

$`125`
   Tree  age circumference
32    5 1004           125

$`139`
   Tree  age circumference
20    3 1372           139

$`140`
   Tree  age circumference
21    3 1582           140

$`142`
   Tree  age circumference
6     1 1372           142
33    5 1231           142

$`145`
  Tree  age circumference
7    1 1582           145

$`156`
   Tree  age circumference
11    2 1004           156

$`167`
   Tree  age circumference
25    4 1004           167

$`172`
   Tree  age circumference
12    2 1231           172

$`174`
   Tree  age circumference
34    5 1372           174

$`177`
   Tree  age circumference
35    5 1582           177

$`179`
   Tree  age circumference
26    4 1231           179

$`203`
   Tree  age circumference
13    2 1372           203
14    2 1582           203

$`209`
   Tree  age circumference
27    4 1372           209

$`214`
   Tree  age circumference
28    4 1582           214

In [42]:
split_data$'30'

Tree age circumference
1  1    118 30           
15 3    118 30           
29 5    118 30

In [44]:
split_data$'75'

Tree age circumference
17 3    664 75

In [60]:
at30 = split_data$'30'
at30
mean(at30$'age')

Tree age circumference
1  1    118 30           
15 3    118 30           
29 5    118 30

[1] 118

In [62]:
at214 = split_data$'214'
at214
mean(at214$'age')

Tree age  circumference
28 4    1582 214

[1] 1582

In [14]:
#### End solution ####


### Save it and push .ipynb and .html file to your Github Repository
## GOOD JOB! You have successfully finished the course!